### ISSUE TITLE
dbclose error on loading Antelope data with waveform

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giseislab/gismotools#27]
```
What steps will reproduce the problem?
- Calling waveform against live AEIC wfdisc tables at UAF. It does not always 
occur, but is a frequent issue. It seems impossible to try...catch this error - 
so perhaps that is already being done at the waveform method level or 
Antelope-MATLAB toolbox level?

What is the expected output? 
- a valid waveform object

What do you see instead?

   ??? Error using dbclose

   Usage: DBCLOSE ( DBPTR )

Please use labels and text to provide additional information.

   There are no calls to dbclose in my code. Code like:
      try
         w = waveform(...)
      catch ME
         disp(ME)
         %do something with ME...
      end
   Fails to catch this error, suggesting it is already being caught at a deeper level or is perhaps at the MEX-file level.

   The upshot is my code breaks whenever this error is thrown.
```

Original issue reported on code.google.com by `gthomp...@alaska.edu` on 5 Oct 2011 at 10:43

**Comment by gthompson** [comment]
It would be useful to capture the actual calls made by waveform to the Antelope Toolbox for MATLAB, isolate the relevant waveform data and database table entries, and then create a standalone issue that could be reported to BRTT. I suspect the error message is being generated in the Antelope compiled C code because there is something wrong with the database integrity. So this problem might link to Issue 28.

**Comment by CelsoReyes** [comment]
in a newer datasource, we can maybe turn on logging of some sort? that
would probably be useful.

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#16
