### ISSUE TITLE
waveform/clean does not run

### ISSUE THREAD

**Issue by gthompson** [giseislab/gismotools#60]
The waveform/clean function does not work with any waveform object I have tried. And I don't understand how it has been rewritten, so not sure how to debug it.

>> w
 
w =
 
 channeltag: .SAKB..HHE        [network.station.location.channel]
      start: 2015-05-27 00:00:00.000
             duration(03:00:00.000)
       data: 1080000 samples
       freq: 100.0000   Hz
      units: null
    history: [1 items], last modification: 17-Sep-2015 16:31:06
    With misc fields...
    * CALIBRATION_APPLIED: NO
    * CALIB: 0
>> clean(w)
Error using horzcat
Dimensions of matrices being concatenated are not consistent.

Error in waveform/clean (line 56)
            firstNans = find(diff([false,nans]) == 1);

**Comment by gthompson** [comment]
I think waveform/clean should be merged into waveform/detrend as a different option/algorithm.
I would say the point should be to improve on the current options in detrend by doing piecewise detrending, and then filling gaps with mean or interpolated values, rather than arbitrarily filling gaps with mean or 0 (effectively introducing spikes into the data) and then detrending. This is conceptual - I haven't measured how much of a problem there really is, and whether this is / how much better the piecewise detrending concept is.

**Comment by CelsoReyes** [comment]
I tend to agree that the idea of clean might belong within another of the
waveform manipulation functions.
The error?  I ran into that implementing the algorithm elsewhere....

to fix, I think it is supposed to be [false; nans]  (semicolon).  If I
remember correctly, somwhere withn the next 2 lines there'll be a similar
issue...    [nans; false]
-Celso

**Comment by gthompson** [comment]
I began looking into this with synthetic data, something like y=x +
randn(size(x))*100
Turns out that y2=detrend(y, 'linear', bp) where bp = find(isnan(y)==1)
doesn't work - still get y2=NaN

Another approach is simply:
y2 = y(~isnan(y))
x2 = x(~isnan(y))

and then detrend(y2)

but then you have irregularly sampled data, so detrending isn't removing a
linear trend in time anymore

so perhaps the best thing really is just to fill gaps by linear
interpolation? Spectrally that will behave differently than "real data" but
still better than spikes introduced with demean+detrend

Of course filling data gaps is a big subject. Model your data, fill gaps
using the model. But for simple cases, say 10 minutes of data with a 30
second gap, maybe linear interpolation is best.
If there is a sine wave trend, then polyfit with degree 2 might be better.

So I might rewrite waveform/clean just to:
1. interpolate missing values
2. detrend

**Comment by CelsoReyes** [comment]
OK. I'm starting to look at this...

**Comment by CelsoReyes** [comment]
First off:  I'm sure at some point I messed up the error in logic on line 27 of detrend.
it should be:
if ~warnedAboutNAN && any(__isnan__(d))

**Comment by gthompson** [comment]
I added a new option to fillgaps. Not pushed yet

**Comment by CelsoReyes** [comment]
Uh oh.  I'm duplicating effort, I think. Sorry!
 I don't want to clutter with weird commits, so I'm just going to mail you my take on the problem.... 


Here's what I've done to your clean function in my attempt to fix the trouble that I'd caused before.

That required some serious attention because of the way that detrend(x, 'linear', dp) still craps out using Nan's.  So, here's the new strategy in a nutshell. I tested it with sine waves and nan's of random lengths. Seems to work beautifully. Of course, I put it back in your court to test.

So, here's the algorithm:
* find the gaps: list of firstNans and lastNans.
* to avoid errors, ignore ends (for now) if data begins/ends with NaNs.
* fill every nan segment with linear trend to connect the dots.  [1 nan nan nan 5] would become:
[1 2 3 4 5]
* detrend linearly.
* replace remaining nan's (at either end ) with linear trend towards 0;

```matlab
z = 1:10000;
w = waveform(channeltag('CR.TMP.00.EHZ'),100,fix(now),(z)+randn(size(z))*100,'nm/s');
d = get(w,'data');
n=0; step = 200; maxgap = 150
while n < (numel(d) - step); 
   n = n + round(rand(1) * step); 
   d(n: n + round(rand(1)*maxgap)) = nan; 
end;
d=d(1:get(w,'data_length'));
gappyw = set(w,'data', d);
plot([gappyw, clean(gappyw)]);
```

**Comment by CelsoReyes** [comment]
it did make for a very interesting problem, though.
