### ISSUE TITLE
"Project Website" link on README is broken

### ISSUE THREAD

**Issue by jkmacc-LANL** [giseislab/gismotools#63]
Title.
Should it be https://github.com/giseislab/gismotools/wiki ?

**Comment by gthompson** [comment]
Hi Jonathan,

You are the PISCES developer, right? I'm very intrigued by that project. Seems like a great combo with ObsPy, which I think you have also contributed too (me also).

Thanks for pointing out this issue. I did update it but in fact we have now moved to a more neutral address:

http://github.com/geoscience-community-codes/GISMO

Since neither Celso or I - nor Garrett - are at the giseislab (UAF Seismology Group).

We haven't "gone live" with the upgrade yet, so we haven't yet started advertising the address.

If you have an interest in contributing to the GISMO toolbox, please let us know. We can give you developer access.

Cheers,

Glenn

**Comment by jkmacc-LANL** [comment]
Hi, Glenn!  Garrett pointed me to this effort, and I'm very happy to hear of new momentum to rally around some common Matlab tools, as seems to have happened in Python with ObsPy.  Thanks for reaching out.  At some point in the future, developer access may be useful, but probably not at present.  

Similarly, I think [Pisces](https://jkmacc-LANL.github.io/pisces) fills an important role, but it's still quite new and could use the help of good developers.  Should you ever be interested to learn more or contribute, I'm also seeking collaborators and PRs.  Thanks!

Best,
Jon

**Comment by gthompson** [comment]
Hi Jon,

Yes, I've written a number of codes to do things like reading CSS3.0 tables and Seisan catalogs into ObsPy Catalog objects, and many other Antelope-related Python codes, and I could well be interested in contributing to Pisces in the future. What directions are you hoping to take with the Pisces project? Email me direct at thompsong at usf.edu

Cheers,

Glenn
